name: Apache Cassandra with multiple racks
description: |
  (Experimental) Cassandra cluster with multiple racks and single DC
version: 2.2.5-rancher1
category: clustering
maintainer: "Autoshift"
minimum_rancher_version: v0.56.0
license:
