zk:
  restart: always
  labels:
    io.rancher.scheduler.affinity:host_label: ${host_label}
    io.rancher.container.hostname_override: container_name
  retain_ip: true
  image: rawmind/rancher-zk:3.4.6-1
  volumes:
  - /opt/zk/data
  environment:
  - JVMFLAGS=-Xmx${zk_mem}m -Xms${zk_mem}m
  - CONFD_INTERVAL=${zk_interval}

kafka:
  restart: always
  labels:
    io.rancher.scheduler.affinity:host_label: ${host_label}
    io.rancher.container.hostname_override: container_name
  retain_ip: true
  image: rawmind/rancher-kafka:0.9.0
  volumes:
  - /opt/kafka/data
  environment:
  - JVMFLAGS=-Xmx${kafka_mem}m -Xms${kafka_mem}m
  - CONFD_INTERVAL=${kafka_interval}
  - ZK_SERVICE=devops/zk
  links:
  - zk

influxdb:
  restart: always
  labels:
    io.rancher.scheduler.affinity:host_label: ${host_label}
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always
  retain_ip: true
  image: autoshift/influxdb-docker:0.12
  environment:
    - ADMIN_USER=root
    - INFLUXDB_INIT_PWD=root
    - PRE_CREATE_DB=telegraf
  mem_limit: 1024000000
  memswap_limit: 1024000000
  cpu_shares: 512

logrotate:
  restart: always
  labels:
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always
  image: autoshift/logrotate
  volumes:
    - /var/lib/docker/containers:/var/lib/docker/containers
  mem_limit: 32000000
  memswap_limit: 32000000
  cpu_shares: 128

ntpd:
  restart: always
  labels:
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always
  image: tutum/ntpd
  privileged: true
  mem_limit: 32000000
  memswap_limit: 32000000
  cpu_shares: 128
