name: Apache Zookeeper
description: |
  (Experimental) Zookeeper cluster
version: 1.5.2-rancher1
category: clustering
maintainer: "Raul Sanchez <rawmind@gmail.com>"
minimum_rancher_version: v0.56.0
license:
